name: Greetings

on:
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Add Comment to Opened Issue
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. 
          Please make sure to read [this issue](https://github.com/Innovateninjas/Paws-frontend/issues/342) for important guidelines. 
          We aim to respond or assign your issue as soon as possible.
