name: Sync Fork with Upstream

on:
  push:
    branches:
      - main  # Replace with your branch name
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          repository: <your-org>/<fork-repo>  # Replace with your fork repository

      - name: Add upstream repository
        run: git remote add upstream https://github.com/Innovateninjas/Paws-frontend.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream changes
        run: git merge upstream/main  # Replace with your branch name

      - name: Push changes to fork
        run: git push origin main  # Replace with your branch name
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
